name: Create Release

on: 
  push:
    tags:
    - '*'

jobs:
  build_and_create_release:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create executable and archive
        run: |
          pyinstaller main.py --name "DNDFogOfWar" --onefile --windowed
          copy dist\DNDFogOfWar.exe .
          Compress-Archive -Path "DNDFogOfWar.exe" -DestinationPath "DNDFogOfWar-v${{ github.ref_name }}.zip"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: DNDFogOfWar-v${{ github.ref_name }}.zip
          tag: "${{ github.ref_name }}"
          name: DNDFogOfWar-v${{ github.ref_name }}
